# -*- coding: utf-8 -*-
"""ObjekBintang2D-MuhamadHafizi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_sgw1pjGuaw_l91x0ogybfjtN2uD5Lu
"""

import numpy as np
import cv2
# from google.colab.patches import cv2_imshow

# Ukuran gambar
width = 500
height = 500

# Membuat gambar kosong
image = np.zeros((height, width, 3), dtype=np.uint8)

# Menggambar bintang
def draw_star(image, center, size, color):
    # Titik-titik sudut bintang
    points = np.array([
        [0, -1],
        [0.35, -0.35],
        [1, 0],
        [0.35, 0.35],
        [0, 1],
        [-0.35, 0.35],
        [-1, 0],
        [-0.35, -0.35]
    ])
    # Skala bintang
    points *= size
    # Geser ke pusat
    points += center
    # Menggambar garis-garis
    for i in range(len(points)):
        # Mengonversi koordinat dari array numpy ke tuple
        pt1 = tuple(points[i].astype(int))
        pt2 = tuple(points[(i + 1) % len(points)].astype(int))
        cv2.line(image, pt1, pt2, color, 2)

# Titik tengah gambar
center = (width // 2, height // 2)
# Ukuran bintang
size = 200
# Warna bintang (biru)
color = (255, 0, 0)

# Menggambar bintang pada gambar
draw_star(image, center, size, color)

# Menampilkan gambar
cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()